sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - node
  - '9'
  - '8'
  - '7'
  - '6'
matrix:
  allow_failures:
    - node_js: '5'
    - node_js: '4'
    - node_js: '0.8'
    - node_js: '0.12'
    - node_js: '0.10'
  fast_finish: true
